"""
Django settings for httpxs project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import datetime
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
from django.conf import settings
from rest_framework.settings import APISettings

from httpAsyncClient.Config import Config

BASE_DIR = Path(__file__).resolve().parent.parent
print(BASE_DIR)
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ky&&(bc%7n9@xu&swf*9&gyvarnv(s+c=v9hw&3l&#*c5sm-a$'
CG_ERP_KEY = 'django-insecure-i)!0q8znw@7vo6ed9c@5@vb^-fm+f2-n)36q2jsk+*2q!iv4j-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'httpAsyncClient',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # token过期拦截
    'public.middleware.user_auth_middleware.TokenAuthMiddleware',
    # 日志
    'public.middleware.LogMiddleware.LogMiddleware'
]
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True
ROOT_URLCONF = 'httpxs.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'httpxs.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mssql',  # 数据库引擎设置
        'NAME': 'cgyypt',  # 要连接的数据库名
        'USER': 'sa',  # 数据库用户名
        'PASSWORD': 'CgSqlServerRoot2012',  # 数据库密码
        'HOST': '172.17.18.110',  # 数据库主机地址
        'PORT': 1433,  # 数据库端口号，默认可以不写 写了连不上....???
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            # 'driver': 'SQL Server Native Client 11.0'
        },
    },
    # 'default': {
    #         'ENGINE': 'mssql',  # 数据库引擎设置
    #         'NAME': 'cgyypt',  # 要连接的数据库名
    #         'USER': 'sa',  # 数据库用户名
    #         'PASSWORD': 'Yun8password@159...',  # 数据库密码
    #         'HOST': '172.17.1.2',  # 数据库主机地址
    #         'PORT': 1433,  # 数据库端口号，默认可以不写 写了连不上....???
    #         'OPTIONS': {
    #             'driver': 'SQL Server Native Client 11.0',
    #         },
    #     },
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


USER_SETTINGS = getattr(settings, 'JWT_AUTH', None)

DEFAULTS = {
    'JWT_PRIVATE_KEY': None,
    'JWT_PUBLIC_KEY': None,
    'JWT_SECRET_KEY': CG_ERP_KEY,
    'JWT_ALGORITHM': 'HS256',
    'JWT_VERIFY': True,
    'JWT_VERIFY_EXPIRATION': True,
    'JWT_LEEWAY': 0,
    'JWT_EXPIRATION_DELTA': datetime.timedelta(days=3),
    'JWT_AUDIENCE': None,
    'JWT_ISSUER': None,
    'JWT_ALLOW_REFRESH': False,
    'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(days=3),
    'JWT_AUTH_HEADER_PREFIX': 'Bearer',

    'PAGE_SIZE': 20,
    # 'ORDER_PAGE_SIZE':5,
    # 'MAX_FILE_UPLOAD_SIZE': 12 * 1000 * 1000,
    # 'GOOGLE_AUTH_ADMIN': "ME4WGNBWGI4GMNLC",
    # 'ZOOM_API_KEY': 'rhfF2x-qRj2QbWNWC5s75w',
    # 'ZOOM_API_SECRET': 'SA7qSdBAwu4MgxEKcYxDrPtdBeoQMtNwWTwN',
    # 'YP_APIKEY': '7be50ac81074413e4d7f6b08fd19eb7e',
    # 'GOOGLE_AUTH_MEMBER': "ME4WGNBWGI4GMNLC",
    # 'GOOGLE_AUTH_MERCHANT': "HAZTMZJRHFSDKODE",
    # 'GOOGLE_AUTH_DAIMAI':"XSBB2PZPRUXINTVA",
    # 'GOOGLE_AUTH_RIDER': "HE2DMNJZMNTDINZX",

}

api_settings = APISettings(USER_SETTINGS, DEFAULTS)


DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 单位为字节数， 10485760值为10M


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False  # 时区 夏令时

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_URL = 'static/'

#上传的文件存放目录位置
MEDIA_ROOT = os.path.join(BASE_DIR, 'static_files/')
#页面访问根路径 相当于 http://127.0.0.1:8000/static_files/
MEDIA_URL = "static_files/"
